baseURL = "https://kevdougful.com/"
languageCode = "en-us"
title = "kevdougful.com"
theme = "Niello"

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[params]
    copyright = "&#xA9; 2019 by kevdougful.com"
